import express from 'express';
import path from 'path';
import dotenv from 'dotenv';
import { GoogleGenAI } from '@google/genai';
import { createServer as createViteServer } from 'vite';
import { getLiveStationsData } from './server/liveService';

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: '10mb' }));

// Lazy initialization of Gemini client
let geminiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI | null {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn('GEMINI_API_KEY is not set. AI features will return deterministic fallback guidance.');
    return null;
  }
  if (!geminiClient) {
    geminiClient = new GoogleGenAI({ apiKey });
  }
  return geminiClient;
}

// Health check endpoint
app.get('/api/health', (req, res) => {
  res.json({
    status: 'ok',
    geminiConfigured: !!process.env.GEMINI_API_KEY,
    timestamp: new Date().toISOString()
  });
});

// Live Official Data Endpoints
app.get('/api/live/stations', async (req, res) => {
  try {
    const stations = await getLiveStationsData();
    res.json({
      status: 'success',
      dataMode: 'LIVE',
      stations
    });
  } catch (error: any) {
    console.error('Error fetching live station data:', error);
    res.status(500).json({
      error: 'Failed to retrieve official live station telemetry',
      message: error.message
    });
  }
});

app.get('/api/live/station/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const stations = await getLiveStationsData();
    const station = stations.find((s) => s.id === id);
    if (!station) {
      return res.status(404).json({ error: `Station ${id} not found` });
    }
    res.json({
      status: 'success',
      dataMode: 'LIVE',
      station
    });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// AquaSentinel Gemini AI Assistant Chat Endpoint
app.post('/api/gemini/aquasentinel-chat', async (req, res) => {
  try {
    const { 
      message, 
      history = [], 
      stationData,
      mode = 'chat', // 'chat' | 'explain_risk' | 'explain_conditions' | 'trend_analysis' | 'whatif' | 'summary'
      language = 'en' // 'en' | 'hi'
    } = req.body;

    const ai = getGeminiClient();

    // Context formatting with explicit Operational Data Mode & Source Status
    const station = stationData || {};
    const dam = station.upstreamDam || {};
    const isLive = station.dataMode === 'LIVE';
    const isHindi = language === 'hi';
    const statusLabel = isLive 
      ? (station.dataSourceStatus === 'STALE_DATA' ? '🔴 STALE DATA' : '🟢 LIVE DATA')
      : '🟡 SIMULATED LIVE DATA — NOT REAL-TIME';

    const sourceDisclaimer = isLive 
      ? 'LIVE DATA MODE (Official CWC/NWIC/IMD Sources). Notice: AquaSentinel is an AI decision-support prototype and is not an official flood-warning system. Always refer to official CWC / IMD / State Disaster Management authorities for official warnings.'
      : 'SIMULATION MODE. Notice: SIMULATED LIVE DATA — NOT REAL-TIME. Values are generated by the simulation engine for scenario testing and demonstration purposes.';

    const contextHeader = `[AQUASENTINEL HYDROLOGICAL CONTEXT - ${isLive ? 'LIVE DATA MODE' : 'SIMULATION MODE'}]
LANGUAGE PREFERENCE: ${isHindi ? 'HINDI (हिंदी) - Respond fluently in natural, empathetic Hindi' : 'ENGLISH - Respond in clear, accessible English'}
OPERATIONAL MODE: ${isLive ? 'LIVE DATA' : 'SIMULATED DATA'}
DATA STATUS BADGE: ${statusLabel}
NOTICE: ${sourceDisclaimer}

Station: ${station.city || 'Unknown Location'} (${station.gaugeStationName || 'Gauge Station'})
River: ${station.riverName || 'River Basin'} | Basin: ${station.basinName || 'Catchment'}
Coordinates: Lat ${station.latitude || 'N/A'}, Lon ${station.longitude || 'N/A'}
Official Benchmark Type: ${station.thresholdType === 'OFFICIAL_CWC' ? 'Official CWC Gauge Threshold' : 'Prototype Configured Threshold'}

[TELEMETRY OBSERVATIONS & MEASUREMENTS]
- Water Level Source: ${station.waterLevelSource || 'CWC / State Hydrology Network'}
- Discharge Source: ${station.dischargeSource || 'Hydrometric Rating Curve'}
- Rainfall Source: ${station.rainfallSource || 'IMD Telemetry'}
- Reservoir Source: ${station.reservoirSource || 'State WRD / Dam Telemetry'}

- Current River Discharge / Flow: ${station.currentFlow !== null && station.currentFlow !== undefined ? `${station.currentFlow.toLocaleString()} m³/s` : 'Data unavailable'}
- Previous Measurement Flow: ${station.previousFlow !== null && station.previousFlow !== undefined ? `${station.previousFlow.toLocaleString()} m³/s` : 'Data unavailable'}
- Flow Surge Rate: ${station.flowChangePercent !== undefined && station.flowChangePercent !== null ? `${station.flowChangePercent > 0 ? '+' : ''}${station.flowChangePercent.toFixed(1)}%` : 'Data unavailable'} ${station.isRapidIncrease ? '(RAPID INCREASE DETECTED >= 25%)' : ''}
- Current River Stage / Water Level: ${station.currentWaterLevel !== null && station.currentWaterLevel !== undefined ? `${station.currentWaterLevel.toFixed(2)} meters` : 'Data unavailable'} (Previous: ${station.previousWaterLevel?.toFixed(2) ?? 'N/A'}m)
- Gauge Thresholds: Normal Stage: ${station.normalStage?.toFixed(2) ?? 'N/A'}m | Alert Stage: ${station.alertStage?.toFixed(2) ?? 'N/A'}m | Warning Stage: ${station.warningStage?.toFixed(2) ?? 'N/A'}m | Critical Stage: ${station.criticalStage?.toFixed(2) ?? 'N/A'}m | Bankfull Level: ${station.bankfullLevel?.toFixed(2) ?? 'N/A'}m
- Catchment Rainfall (24h): ${station.rainfall24h !== null && station.rainfall24h !== undefined ? `${station.rainfall24h} mm` : 'Data unavailable'}

[UPSTREAM DAM / BARRAGE TELEMETRY]
- Name: ${dam.name || 'No Direct Upstream Dam'} (Distance: ${dam.distanceUpstreamKm ? `${dam.distanceUpstreamKm} km upstream` : 'N/A'})
- Telemetry Status: ${dam.isAvailable ? 'ACTIVE TELEMETRY' : 'DATA UNAVAILABLE (Rainfall-driven catchment; no direct upstream storage dam)'}
- Reservoir Level: ${dam.reservoirLevelPercent !== null && dam.reservoirLevelPercent !== undefined ? `${dam.reservoirLevelPercent}% (${dam.reservoirElevationMeters ?? 'N/A'} m a.s.l.)` : 'Data unavailable'}
- Dam Discharge / Outflow: ${dam.dischargeM3s !== null && dam.dischargeM3s !== undefined ? `${dam.dischargeM3s.toLocaleString()} m³/s` : 'Data unavailable'}
- Previous Dam Outflow: ${dam.previousDischargeM3s !== null && dam.previousDischargeM3s !== undefined ? `${dam.previousDischargeM3s.toLocaleString()} m³/s` : 'Data unavailable'}
- Gate / Spillway Status: ${dam.gateStatus || 'Data unavailable'}
- Hydraulic Travel Time to Station: ${dam.travelTimeToStationHours ? `~${dam.travelTimeToStationHours} hours` : 'N/A'}

[DETERMINISTIC RULE-BASED RISK ENGINE CALCULATION]
- Algorithmic Flood Risk Index: ${station.riskScore ?? 'N/A'}/100
- Risk Level: ${station.riskLevel || 'NORMAL'}
- Factor Breakdown: Water Level (${station.riskFactors?.waterLevelFactor ?? 0}/100), Flow Volume (${station.riskFactors?.flowFactor ?? 0}/100), Surge Rate (${station.riskFactors?.surgeRateFactor ?? 0}/100), Dam Release (${station.riskFactors?.damFactor ?? 0}/100), Catchment Rainfall (${station.riskFactors?.rainfallFactor ?? 0}/100)
- Dominant Risk Driver: ${station.riskFactors?.dominantDriver || 'Normal Hydrological Baseflow'}
- Observation Timestamp: ${station.lastTelemetryUpdate || 'Current cycle'}
`;

    if (!ai) {
      // Deterministic, grounded fallback response when API key is missing
      const badgeText = isLive ? '🟢 LIVE DATA MODE' : '🟡 SIMULATED LIVE DATA — NOT REAL-TIME';
      let reply = '';
      
      if (isHindi) {
        if (mode === 'explain_risk' || message?.toLowerCase().includes('risk') || message?.includes('जोखिम')) {
          reply = `### ${station.city} (${station.riverName}) के लिए जल वैज्ञानिक स्थिति व जोखिम विश्लेषण\n\n` +
            `**[ ${badgeText} ]**\n\n` +
            `**वर्तमान गणना स्तर:** **${station.riskLevel === 'NORMAL' ? 'सामान्य (NORMAL)' : station.riskLevel === 'WATCH' ? 'निगरानी (WATCH)' : station.riskLevel === 'WARNING' ? 'चेतावनी (WARNING)' : 'गंभीर (CRITICAL)'}** (स्कोर: ${station.riskScore ?? 0}/100)\n\n` +
            `**मुख्य स्थिति विवरण:**\n` +
            `- **नदी का बहाव (Discharge):** ${station.currentFlow !== null ? `${station.currentFlow?.toLocaleString()} m³/s` : 'डेटा उपलब्ध नहीं'} (बदलाव: ${station.flowChangePercent > 0 ? '+' : ''}${station.flowChangePercent?.toFixed(1)}%).\n` +
            `- **जलस्तर (Water Level):** ${station.currentWaterLevel !== null ? `${station.currentWaterLevel?.toFixed(2)} मीटर` : 'डेटा उपलब्ध नहीं'} (चेतावनी स्तर: ${station.warningStage?.toFixed(2)}m, खतरे का निशान: ${station.criticalStage?.toFixed(2)}m).\n` +
            `- **अपस्ट्रीम बांध:** ${dam.isAvailable && dam.dischargeM3s ? `${dam.dischargeM3s?.toLocaleString()} m³/s (${dam.name})` : 'डेटा उपलब्ध नहीं या सीधा बांध नहीं है'}.\n` +
            `- **24 घंटे की वर्षा:** ${station.rainfall24h !== null ? `${station.rainfall24h} मिमी` : 'डेटा उपलब्ध नहीं'}.\n\n` +
            `**सलाह:** कृपया आधिकारिक राज्य आपदा प्रबंधन (SDMA / CWC) के निर्देशों का पालन करें।\n\n` +
            `*सूचना: AquaSentinel एक AI निर्णय-समर्थन प्रोटोटाइप है, आधिकारिक चेतावनी प्रणाली नहीं।*`;
        } else {
          reply = `**${station.city} (${station.riverName}) की स्थिति [${badgeText}]:**\n\n` +
            `- नदी का वर्तमान बहाव **${station.currentFlow !== null ? `${station.currentFlow?.toLocaleString()} m³/s` : 'डेटा उपलब्ध नहीं'}** है (${station.flowChangePercent > 0 ? '+' : ''}${station.flowChangePercent?.toFixed(1)}% बदलाव).\n` +
            `- नदी का जलस्तर **${station.currentWaterLevel !== null ? `${station.currentWaterLevel?.toFixed(2)} मीटर` : 'डेटा उपलब्ध नहीं'}** है (चेतावनी निशान: ${station.warningStage?.toFixed(2)}m).\n` +
            `- वर्तमान जोखिम स्तर: **${station.riskLevel === 'NORMAL' ? 'सामान्य (NORMAL)' : station.riskLevel === 'WATCH' ? 'निगरानी (WATCH)' : station.riskLevel === 'WARNING' ? 'चेतावनी (WARNING)' : 'गंभीर (CRITICAL)'}** (${station.riskScore}/100).\n\n` +
            `क्या आप किसी विशेष पैरामीटर (जैसे वर्षा, बांध या सुरक्षा सुझाव) के बारे में जानना चाहते हैं?`;
        }
      } else {
        if (mode === 'explain_risk' || message?.toLowerCase().includes('risk')) {
          reply = `### Hydrological Risk Assessment for ${station.city} (${station.riverName})\n\n` +
            `**[ ${badgeText} ]**\n\n` +
            `**Current Calculated Risk Status:** **${station.riskLevel || 'NORMAL'}** (Score: ${station.riskScore ?? 0}/100)\n\n` +
            `**What Changed & Why:**\n` +
            `- **Current River Discharge:** ${station.currentFlow !== null ? `${station.currentFlow?.toLocaleString()} m³/s` : 'Data unavailable'} (Change: ${station.flowChangePercent > 0 ? '+' : ''}${station.flowChangePercent?.toFixed(1)}% vs previous reading of ${station.previousFlow?.toLocaleString()} m³/s).\n` +
            `- **Water Stage:** ${station.currentWaterLevel !== null ? `${station.currentWaterLevel?.toFixed(2)}m` : 'Data unavailable'} (Warning Stage: ${station.warningStage?.toFixed(2)}m, Critical Stage: ${station.criticalStage?.toFixed(2)}m).\n` +
            `- **Upstream Dam Discharge:** ${dam.isAvailable && dam.dischargeM3s ? `${dam.dischargeM3s?.toLocaleString()} m³/s (${dam.name})` : 'Data unavailable / No upstream storage dam'}.\n` +
            `- **Catchment Rainfall:** ${station.rainfall24h !== null ? `${station.rainfall24h} mm` : 'Data unavailable'}.\n\n` +
            `**What to Monitor:** Keep watching the rate of flow change and whether river stage approaches the ${station.warningStage?.toFixed(2)}m warning mark.\n\n` +
            `*${isLive ? 'Disclaimer: AquaSentinel is an AI decision-support prototype and is not an official flood-warning system. Always refer to official CWC / IMD / State Disaster Management authorities.' : 'Notice: SIMULATED LIVE DATA — NOT REAL-TIME'}*`;
        } else if (mode === 'summary' || message?.toLowerCase().includes('summar')) {
          reply = `### Situational Briefing: ${station.city} — ${station.riverName}\n\n` +
            `*Notice: ${badgeText}*\n\n` +
            `- **Discharge:** ${station.currentFlow !== null ? `${station.currentFlow?.toLocaleString()} m³/s` : 'Data unavailable'} (${station.isRapidIncrease ? '⚠️ RAPID SURGE DETECTED' : 'Steady flow'})\n` +
            `- **Water Level:** ${station.currentWaterLevel !== null ? `${station.currentWaterLevel?.toFixed(2)}m` : 'Data unavailable'} relative to normal stage (${station.normalStage?.toFixed(2)}m)\n` +
            `- **Upstream Dam (${dam.name || 'Dam'}):** ${dam.isAvailable && dam.dischargeM3s ? `${dam.dischargeM3s?.toLocaleString()} m³/s (${dam.gateStatus})` : 'Data unavailable / No direct upstream storage dam'}\n` +
            `- **Flood Risk Level:** **${station.riskLevel}** (${station.riskScore}/100)`;
        } else {
          reply = `Based on the latest ${isLive ? 'official telemetry' : 'simulated telemetry'} for **${station.city} (${station.riverName})** *(${badgeText})*:\n\n` +
            `- River flow: **${station.currentFlow !== null ? `${station.currentFlow?.toLocaleString()} m³/s` : 'Data unavailable'}**, compared to **${station.previousFlow?.toLocaleString()} m³/s** previously (${station.flowChangePercent > 0 ? '+' : ''}${station.flowChangePercent?.toFixed(1)}%).\n` +
            `- Water stage: **${station.currentWaterLevel !== null ? `${station.currentWaterLevel?.toFixed(2)} meters` : 'Data unavailable'}** (Warning mark: ${station.warningStage?.toFixed(2)}m).\n` +
            `- Upstream ${dam.name || 'Dam'}: ${dam.isAvailable && dam.dischargeM3s ? `releasing ${dam.dischargeM3s?.toLocaleString()} m³/s` : (dam.isAvailable ? 'Normal regulated release' : 'Data unavailable (No direct upstream storage dam)')}.\n` +
            `- Current calculated risk indicator: **${station.riskLevel}** (${station.riskScore}/100).\n\n` +
            `Would you like me to explain what to monitor next or inspect another station?`;
        }
      }

      return res.json({
        reply,
        mode,
        isFallback: true
      });
    }

    const systemInstruction = `You are "AquaSentinel Assistant", a professional Hydrological, River, Dam, and Flood Risk Monitoring AI safety companion.

CRITICAL INSTRUCTIONS & ACCURACY MANDATES:
1. **LANGUAGE SUPPORT**:
   - If LANGUAGE PREFERENCE is HINDI: You MUST write your entire answer in fluent, clear, natural Hindi (देवनागरी लिपि). Use understandable terms (जैसे 'जलस्तर', 'नदी का बहाव', 'चेतावनी स्तर', 'जोखिम').
   - If LANGUAGE PREFERENCE is ENGLISH: Write in clean, accessible English free of unnecessarily dense hydrologic jargon.
2. **OPERATIONAL MODE AWARENESS**:
   - If the data is SIMULATED: Always include the disclaimer: "${isHindi ? 'यह सिम्युलेटेड डेटा है — वास्तविक समय का नहीं।' : 'SIMULATED LIVE DATA — NOT REAL-TIME'}". Never claim simulated data is real.
   - If the data is LIVE: Include official source attributions and the safety disclaimer: "${isHindi ? 'AquaSentinel एक AI निर्णय-समर्थन प्रोटोटाइप है, आधिकारिक बाढ़ चेतावनी प्रणाली नहीं।' : 'AquaSentinel is an AI decision-support prototype and is not an official flood-warning system. Always refer to official CWC / IMD / State Disaster Management authorities.'}"
3. **NO FABRICATION OF MISSING DATA**:
   - If a measurement is "Data unavailable" or null (e.g. upstream dam for Dehradun where no upstream storage reservoir exists), clearly state that data is unavailable or not applicable. NEVER invent dam release numbers, station IDs, or river levels.
4. **DETERMINISTIC RISK SCORE INTEGRITY**:
   - Do NOT invent, recalculate, or guess the fundamental risk score or risk level. Use the provided deterministic mathematical score (0-100) and risk level (NORMAL/WATCH/WARNING/CRITICAL) exactly as calculated by the risk engine.
5. **EXPLAIN IN SIMPLE, REASSURING LANGUAGE**:
   - What is happening right now? (current water level, flow trend, rainfall, dam release).
   - Is there a flood risk? Why does the risk level exist? (which factor was the dominant driver).
   - What should residents/authorities monitor next? (e.g. rate of increase, warning threshold, rain forecast).
   - For emergencies: Direct users to official civil defense helpline (112 / 1070 / 1077) and official disaster response teams.
6. **STRUCTURE & TONE**: Friendly, plain language first, objective, calm, and structured with concise Markdown formatting.`;

    const contents: any[] = [];

    if (history.length === 0) {
      contents.push({
        role: 'user',
        parts: [{ text: `${contextHeader}\n\nUser Question: ${message || (isHindi ? 'कृपया वर्तमान स्थिति और नदी के स्तर के बारे में बताएं।' : 'Please explain the current river and flood risk conditions.')}` }]
      });
    } else {
      const firstMsg = history[0];
      contents.push({
        role: firstMsg.role === 'assistant' ? 'model' : 'user',
        parts: [{ text: `${contextHeader}\n\n${firstMsg.content}` }]
      });

      for (let i = 1; i < history.length; i++) {
        contents.push({
          role: history[i].role === 'assistant' ? 'model' : 'user',
          parts: [{ text: history[i].content }]
        });
      }

      if (message) {
        contents.push({
          role: 'user',
          parts: [{ text: message }]
        });
      }
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents,
      config: {
        systemInstruction,
        temperature: 0.3, // Low temperature for high factual accuracy
        maxOutputTokens: 1200
      }
    });

    const reply = response.text || (isHindi ? 'स्थिति का विश्लेषण किया गया है। कृपया बताएं कि आप किस जानकारी के बारे में विस्तार से जानना चाहते हैं।' : 'Telemetry analyzed. Please specify what hydrological parameter you would like to inspect.');

    res.json({
      reply,
      mode,
      isFallback: false
    });
  } catch (error: any) {
    console.error('AquaSentinel Gemini Chat Error:', error);
    res.status(500).json({
      error: error.message || 'Failed to process AI explanation',
      reply: 'AquaSentinel telemetry engine encountered a temporary connection issue. Please retry in a moment.'
    });
  }
});

// Single-shot Basin Summary Briefing Endpoint
app.post('/api/gemini/basin-summary', async (req, res) => {
  try {
    const { stationData } = req.body;
    const ai = getGeminiClient();
    const station = stationData || {};
    const dam = station.upstreamDam || {};
    const isLive = station.dataMode === 'LIVE';

    if (!ai) {
      return res.json({
        summary: `**Current Status: ${station.riskLevel || 'NORMAL'} (${station.riskScore || 0}/100)** [${isLive ? 'LIVE DATA' : 'SIMULATED DATA'}]\n` +
          `River discharge at **${station.currentFlow !== null ? `${station.currentFlow?.toLocaleString()} m³/s` : 'Data unavailable'}** with water level at **${station.currentWaterLevel !== null ? `${station.currentWaterLevel?.toFixed(2)}m` : 'Data unavailable'}** (Warning stage: ${station.warningStage?.toFixed(2)}m).\n` +
          `Upstream ${dam.name || 'Dam'}: ${dam.isAvailable && dam.dischargeM3s ? `${dam.dischargeM3s?.toLocaleString()} m³/s discharge` : 'Data unavailable / No upstream reservoir'}.\n` +
          `Dominant Driver: ${station.riskFactors?.dominantDriver || 'Hydrological baseflow'}.`,
        keyPoints: [
          `Flow change: ${station.flowChangePercent > 0 ? '+' : ''}${station.flowChangePercent?.toFixed(1)}% vs previous measurement`,
          `Current stage: ${station.currentWaterLevel !== null ? `${station.currentWaterLevel?.toFixed(2)}m` : 'Data unavailable'} (Critical threshold: ${station.criticalStage?.toFixed(2)}m)`,
          station.isRapidIncrease ? '⚠️ Rapid flow surge detected in recent hours' : 'Flow rates within steady progression boundaries'
        ]
      });
    }

    const prompt = `Generate a concise, high-priority hydrological briefing for the following station:

OPERATIONAL MODE: ${isLive ? 'LIVE DATA (Official CWC/NWIC/IMD Sources)' : 'SIMULATION MODE (Simulated Live Data)'}
Station: ${station.city} (${station.riverName})
Gauge: ${station.gaugeStationName}
Current Flow: ${station.currentFlow !== null ? `${station.currentFlow} m³/s` : 'Data unavailable'} (Previous: ${station.previousFlow} m³/s, Change: ${station.flowChangePercent}%)
Surge Flag: ${station.isRapidIncrease ? 'RAPID INCREASE DETECTED' : 'Normal variation'}
Water Level: ${station.currentWaterLevel !== null ? `${station.currentWaterLevel}m` : 'Data unavailable'} (Normal: ${station.normalStage}m, Warning: ${station.warningStage}m, Critical: ${station.criticalStage}m)
24h Catchment Rainfall: ${station.rainfall24h !== null ? `${station.rainfall24h} mm` : 'Data unavailable'}
Upstream Dam (${dam.name}): ${dam.isAvailable ? `Discharge ${dam.dischargeM3s} m³/s, Status: ${dam.gateStatus}` : 'Data unavailable / No direct upstream storage dam'}
Calculated Risk Index: ${station.riskScore}/100 (${station.riskLevel})
Dominant Factor: ${station.riskFactors?.dominantDriver}

Return JSON with:
"summary": A 2-3 sentence executive situational summary highlighting the risk level and most significant metric shift. Note ${isLive ? 'live official data' : 'simulated data'}.
"keyPoints": An array of 3-4 bullet strings identifying specific telemetry observations and monitoring recommendations.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      config: {
        responseMimeType: 'application/json',
        temperature: 0.2
      }
    });

    try {
      const parsed = JSON.parse(response.text || '{}');
      res.json({
        summary: parsed.summary || 'Hydrological briefing generated from latest station telemetry.',
        keyPoints: Array.isArray(parsed.keyPoints) ? parsed.keyPoints : []
      });
    } catch {
      res.json({
        summary: response.text || 'Briefing generated.',
        keyPoints: []
      });
    }
  } catch (error: any) {
    console.error('Basin summary error:', error);
    res.status(500).json({
      error: 'Failed to generate basin summary',
      summary: 'Situational summary temporarily unavailable.',
      keyPoints: []
    });
  }
});

// What-If Scenario Hydrological Assessment Endpoint
app.post('/api/gemini/whatif-analysis', async (req, res) => {
  try {
    const { scenarioData, stationData } = req.body;
    const ai = getGeminiClient();

    const scenario = scenarioData || {};
    const station = stationData || {};

    if (!ai) {
      return res.json({
        assessment: `### Hypothetical Scenario Evaluation (HYPOTHETICAL ESTIMATE)\n\n` +
          `Under this simulated condition (+${scenario.flowDeltaPercent}% river flow, +${scenario.additionalDamDischargeM3s || 0} m³/s dam release):\n` +
          `- **Projected Flow:** ~${scenario.projectedFlow?.toLocaleString()} m³/s (Baseline: ${scenario.baselineFlow?.toLocaleString()} m³/s)\n` +
          `- **Projected Water Stage:** ~${scenario.projectedWaterLevel?.toFixed(2)}m (Baseline: ${scenario.baselineWaterLevel?.toFixed(2)}m)\n` +
          `- **Simulated Risk Shift:** Score changes from ${scenario.baselineRiskScore}/100 (${station.riskLevel}) to **${scenario.projectedRiskScore}/100 (${scenario.projectedRiskLevel})** (Δ ${scenario.riskDelta > 0 ? '+' : ''}${scenario.riskDelta} pts).\n\n` +
          `*Notice: This is a scenario calculation model for planning purposes and NOT a real prediction or meteorological forecast.*`
      });
    }

    const prompt = `You are AquaSentinel Hydrology Engine. Provide a scenario impact assessment for this HYPOTHETICAL What-If simulation:

Station: ${station.city} (${station.riverName})
Simulated Parameters:
- Flow Delta: ${scenario.flowDeltaPercent >= 0 ? '+' : ''}${scenario.flowDeltaPercent}%
- Additional Dam Discharge: +${scenario.additionalDamDischargeM3s || 0} m³/s
- Additional Catchment Rain: +${scenario.additionalRainfallMm || 0} mm

Model Projections:
- Baseline Flow: ${scenario.baselineFlow} m³/s -> Projected Flow: ${scenario.projectedFlow} m³/s
- Baseline Water Level: ${scenario.baselineWaterLevel}m -> Projected Stage: ${scenario.projectedWaterLevel}m
- Warning Stage: ${station.warningStage}m | Critical Stage: ${station.criticalStage}m | Bankfull Level: ${station.bankfullLevel}m
- Risk Score Shift: ${scenario.baselineRiskScore}/100 (${station.riskLevel}) -> ${scenario.projectedRiskScore}/100 (${scenario.projectedRiskLevel})

Format the response in clear Markdown with:
1. Clear disclaimer: **HYPOTHETICAL SIMULATION ESTIMATE (Not a Real Forecast)**
2. **Channel Capacity & Stage Impact**: Explain how the river cross-section accommodates the extra volume and whether bankfull/warning thresholds are breached.
3. **Upstream Travel & Wave Lag**: Discuss wave propagation and delay considerations.
4. **Vulnerability & Preparedness Insights**: Practical mitigation or monitoring priorities under such a hypothetical condition.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      config: {
        temperature: 0.3,
        maxOutputTokens: 1000
      }
    });

    res.json({
      assessment: response.text || 'Scenario evaluation completed.'
    });
  } catch (error: any) {
    console.error('What-If evaluation error:', error);
    res.status(500).json({
      error: 'Failed to evaluate scenario',
      assessment: 'Hypothetical evaluation encountered a calculation error. Please try adjusting your parameters.'
    });
  }
});

async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server listening on http://0.0.0.0:${PORT}`);
  });
}

startServer();
